### ISSUE TITLE
Enormous logs

### ISSUE THREAD

**Issue by AntoineDavidSupersoniks** [bokysan/docker-postfix#110]
Hi,

I've specified in my .env file the following directives :

```env
POSTFIX_FORCE_COLOR=1
POSTFIX_INBOUND_DEBUGGING=0
POSTFIX_LOG_FORMAT=plain
POSTFIX_LOG_FILE="/var/log/postfix.log"
```

So far so good, and i've my log file in my container available at /var/log/postfix.log

But a few months later my postflix.log is 3.5GB and still growing.

I've read the dockerfile but I see nowhere a logrotate.

How solve this situation ?

Best regards

**Comment by AntoineDavidSupersoniks** [comment]
Other question,

Why i've not the same thing between :
`docker logs postfix` and the custom log : `/var/log/postfix.log`

Thanks

**Comment by bokysan** [comment]
> I've read the dockerfile but I see nowhere a logrotate.

Frankly, I don't see this to be in the scope of the image. This image is not a fully-fledged OS. Consequentially, it doesn't run any cron jobs, nor it has the capability to do so -- this would be just unnecessary bloat.

You can solve your problem using two different approaches:

1. Postfix does include a [logrotate command](https://www.postfix.org/MAILLOG_README.html), but, as said, cron is not part of the image. You could, for example, create a file `/etc/cron.daily/postfix-logrotate` on your system, which would run `docker exec -t postfix postfix logrotate` or [create another container|https://www.howtogeek.com/devops/how-to-use-cron-with-your-docker-containers/] in your `docker-compose.yaml` which would run it for you, if you want a more contained solution.
2. Instead of outputting to a file, leave the output to stdout and either [limit the size of the output](https://stackoverflow.com/questions/39078715/specify-max-log-json-file-size-in-docker-compose) or install a tool like [fluentd](https://docs.docker.com/config/containers/logging/fluentd/) to collect your logs.

> Why i've not the same thing between : `docker logs postfix` and the custom log : `/var/log/postfix.log`

Because output of `docker logs postfix` shows the output of all services -- e.g. DKIM included. You have redirected only postfix logs to a log file.

**Comment by AntoineDavidSupersoniks** [comment]
Thank you for your quick response.

> Instead of outputting to a file, leave the output to stdout and either [limit the size of the output](https://stackoverflow.com/questions/39078715/specify-max-log-json-file-size-in-docker-compose) or install a tool like [fluentd](https://docs.docker.com/config/containers/logging/fluentd/) to collect your logs.

I was just studying this

If I don't define `POSTFIX_LOG_FILE` the postfix logs will only be in the stdout ?

Cordialy

**Comment by bokysan** [comment]
> If I don't define POSTFIX_LOG_FILE the postfix logs will only be in the stdout ?

Yes.

**Comment by AntoineDavidSupersoniks** [comment]
wonderfull !

And with deactivation of the healthcheck logs it will be more clear.

Thanks for your answers !
