### ISSUE TITLE
Feature request: Add possibility for outbound debugging

### ISSUE THREAD

**Issue by frankhetterich** [bokysan/docker-postfix#157]
There is already an option to activate the smtp inbound debugging with `INBOUND_DEBUGGING=1`  

It would be good to have also such an option for outbound connections, so it´s easier to debug issues with relay servers (e.g. if TLS is used or not)

**Comment by bokysan** [comment]
Hi,

`INBOUND_DEBUGGING` is just a shorthand that sets [`debug_peer_list`](https://www.oreilly.com/library/view/postfix-the-definitive/0596002122/re18.html) to the list in `mynetworks`.

To debug outbound connections, you would literary need to list the whole internet here.

Instead of this, I'd suggest manually setting `debug_peer_list` and `debug_peer_level` to your preferred values. This is out of scope of this image and is part of how postfix itself is configured.

See more info here: https://mirror.math.princeton.edu/pub/postfix/postconf.5.html
