### ISSUE TITLE
Change all FROM addresses

### ISSUE THREAD

**Issue by NMichas** [bokysan/docker-postfix#213]
Hello,

Is it possible to change the FROM address of all/any incoming mail to something else I specify? I don't need any fancy mappings or similar, just to apply this rule to everything incoming.

Thanks ❤️

**Comment by bokysan** [comment]
Hi @NMichas,

Thank you for your message. Unfortunately, this question has nothing to do with this image but with postfix configuration.

Due to time constrains I'm unable to provide free postfix consultation services.

That being said, this is easily solvable. Google is your friend. Start here: https://www.google.com/search?q=postfix+rewrite+from+address&oe=utf-8
