### ISSUE TITLE
Warning: sasl-xoauth2

### ISSUE THREAD

**Issue by tobiasbp** [bokysan/docker-postfix#47]
Update: I was running _latest_. Changed to _v2.2.1_. Issues is resolved. Sorry for the noise.

Running the image in Kubernetes, I get the following in the log when a mail is sent via the relay:
```
2020-12-01T12:35:01.179654+00:00 WARNING postfix/smtp[186]: sasl-xoauth2: Unable to open config file /etc/sasl-xoauth2.conf: No such file or directory
2020-12-01T12:35:01.183058+00:00 WARNING postfix/smtp[186]: sasl_client_add_plugin(): entry_point(): failed for plugname sasl-xoauth2
```
Looking in the _Dockerfile_ for _docker-postfix_, version 0.9 of _xoauth_ is to be downloaded, but the latest version in that repo is 0.8? >  https://github.com/tarickb/sasl-xoauth2/releases

```
ARG SASL_XOAUTH2_REPO_URL=https://github.com/tarickb/sasl-xoauth2.git
ARG SASL_XOAUTH2_GIT_REF=release-0.9
```

**Comment by tobiasbp** [comment]
Changing from _latest_ to _v2.2.1_ resolved he issue.

**Comment by galakhov** [comment]
I am getting the same warning. Is /etc/sasl-xoauth2.conf being copied to /etc/ during `make` in [Dockerfile](https://github.com/bokysan/docker-postfix/blob/master/Dockerfile#L15)?
It seems like the 'release-1.10' actually exists, as this one works: `git clone --depth 1 --branch release-0.10 https://github.com/tarickb/sasl-xoauth2.git ./sasl-xoauth2`.

So one would only need to set these environment variables in order to get rid of these warnings: 'XOAUTH2_CLIENT_ID' and 'XOAUTH2_SECRET'?

What if I use `POSTFIX_smtp_sasl_security_options=noanonymous` like in this config [here](https://github.com/bokysan/docker-postfix/issues/51) without the environment variables from above?
