### ISSUE TITLE
smtpd_tls_security_level  property not exposed

### ISSUE THREAD

**Issue by codyprashant** [bokysan/docker-postfix#54]
I was testing my Java application using postfix for relaying emails from App to postfix and then to AWS SES.

I am not able to send an email when my Java app also uses TLS certificate to send an email to postfix and receiving error stating 

> Caused by: javax.mail.MessagingException: Server doesn't support required transport level security
>         at org.apache.geronimo.javamail.transport.smtp.SMTPConnection.sendHandshake(SMTPConnection.java:811) ~[geronimo-javamail_1.4_mail-1.8.4.jar:1.8.4]
>         at org.apache.geronimo.javamail.transport.smtp.SMTPConnection.protocolConnect(SMTPConnection.java:149) ~[geronimo-javamail_1.4_mail-1.8.4.jar:1.8.4]
>         at org.apache.geronimo.javamail.transport.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:165) ~[geronimo-javamail_1.4_mail-1.8.4.jar:1.8.4]

I believe exposing **smtpd_tls_security_level** property may solve this issue. Also, I believe we will require another field to set TLS certs as well.

Please suggest if there are any other solutions for achieving the same

**Comment by bokysan** [comment]
Just using `docker -e POSTFIX_smtpd_tls_security_level=none ...` doesn't work for you as [per documentation](https://github.com/bokysan/docker-postfix#overriding-specific-postfix-settings)?

**Comment by codyprashant** [comment]
I mean if we can have something in helm charts. So We can use Helm chart directly.

**Comment by bokysan** [comment]
Using [config.general](https://github.com/bokysan/docker-postfix/blob/master/helm/mail/values.yaml#L72), e.g.:

```
config:
  general:
    POSTFIX_smtpd_tls_security_level: none
```

doesn't work?

**Comment by codyprashant** [comment]
I tried with the same but still not able to make connections. After digging up postfix logs, I found below warning

2021-02-08T13:29:48.645112+00:00 WARNING postfix/smtpd[204]: warning: No server certs available. TLS won't be enabled

Any suggestions on that, Sorry for noob questions, I am new to postfix and still learning.

**Comment by bokysan** [comment]
According to the documentation, [smtpd_tls_security_level](http://www.postfix.org/postconf.5.html#smtpd_tls_security_level) is meant for cases where you need to authenticate the connection between the client (you application) and postfix. Since this image is designed to be used for outgoing queue -- *in secure environments* --  no such feature is built-in directly into the image.

You can, however, configure it at your own discretion by specifying `smtpd_tls_security_level = encrypt` or `smtpd_tls_security_level = may`. If you do this, you will need to configure the [smtpd_tls_key_file](http://www.postfix.org/postconf.5.html#smtpd_tls_security_level) and [smtpd_tls_cert_file](http://www.postfix.org/postconf.5.html#smtpd_tls_cert_file) as well. Of course, if you do that, you will need to import the said certificate into your Java app, otherwise you will get certificate errors and dropped connections. There are tutorials online on how to generate self-signed certificates.

If you are running in a secure environment, I highly suggest you don't encrypt connections between Postfix and your app. Most of the time it's simply not worth the bother and will make your life much easier. For JavaMail I haven't tried it out -- writing from the top of my head -- but something like this ought to do the trick:

```java
Properties props = new Properties();
props.put("mail.smtp.auth", "false");
props.put("mail.smtp.starttls.enable", "false");
props.put("mail.smtp.starttls.required", "false");
props.put("mail.smtp.host", "<your-postfix-server>");
props.put("mail.smtp.port", "587");

Session session = Session.getInstance(props, ...)
```

See more on [java mail website](https://javaee.github.io/javamail/docs/api/com/sun/mail/smtp/package-summary.html#properties).

**Comment by bokysan** [comment]
Closing this issue as INVALID as `smtpd_tls_security_level` is property not exposed.
