### ISSUE TITLE
Question: How to scale down without losing emails?

### ISSUE THREAD

**Issue by Nuru** [bokysan/docker-postfix#63]
This wonderful chart supports autoscaling, but I do not see any provisions for scaling down without losing emails. Actually, they will not be totally lost, but if the replica set scales from 3 to 2, meaning replica-2 disappears, then if it is shut down before draining its queue there will be emails abandoned on persistent-volume-2 until the replica set scales back up. Is there a way to manage the scale-down so that the pod stops accepting new requests while the queue drains, and the pod is not terminated until the queue is empty?

**Comment by bokysan** [comment]
I'm leaving this issue open until we find an appropriate solution.

The image currently uses `supervisord`. Postfix call could be replaced by a bash script which catches `SIGTERM` and forces queue flush. If this sounds a bit sketch it's because it is -- I don't think we have a good way at this stage of waiting for the queue to clear.

Further exploration of this issue is needed. If anybody has any suggestions, I'm open to ideas.

**Comment by komasoftware** [comment]
This is interesting for this discussion : https://medium.com/@marko.luksa/graceful-scaledown-of-stateful-apps-in-kubernetes-2205fc556ba9

**Comment by bokysan** [comment]
This post is over three years old, which is ages in Kubernetes world. I'll talk with @luksa if he has any new ideas -- luckly he lives closeby. :-)

**Comment by bokysan** [comment]
I think the `lifecycle` definition should help fix this issue -- please check if the latest master works for you.
