### ISSUE TITLE
Restart on every update

### ISSUE THREAD

**Issue by bcroq** [bokysan/docker-postfix#71]
Is there a reason why the pods are re-created on every `helm update`?

I know that the date in `date/deploy-date` is the reason why k8s re-creates the pods, but why did you choose to ask for a new pod on each update?

**Comment by bokysan** [comment]
Because otherwise postfix won't get reloaded if any configs are changed. I do expect many more issues with people changing the config and not seeing it applied than knowing that they need to do a `SIGHUP` on all postfix and opendkim instances.

One option would be to send a `SIGHUP` to all running instances from a `post-update` job, but that would require quite a bit more coding. If you're willing to submit a patch, pull requests are welcome.

**Comment by bcroq** [comment]
Could there be a value that would disable this restart once you know your configuration is stable?

**Comment by bokysan** [comment]
Sure, there could be an option `values.yml` to disable injecting of `date/deploy-date`, but that would be at your own risk and I wouldn't be able to support support it.

May I ask what the use case it, as usually people don't need to redeploy the chart very often?

**Comment by bcroq** [comment]
This chart is used as a dependency in a umbrella chart so each time our application is upgraded its mail relay is restarted and is unavailable for a few seconds.

Now that the mail relay configuration is done, it would be great to keep it running when our application is upgraded.

**Comment by bokysan** [comment]
I will look into it but running at least two instances should resolve your issue -- kubernetes will do a rolling deployment and your mail relay will have 100% uptime.

**Comment by bcroq** [comment]
As proposed, I currently deploy using 2 replicas; rolling deployments make sure at least one pod is running.

I see you added `recreateOnRedeploy` in 3.3.0. I test it as soon as possible.

Thanks!

**Comment by bcroq** [comment]
Tested and works as expected.
